### ISSUE TITLE
Request - Dockerfile

### ISSUE THREAD

**Issue by undaunt** [harsh98trivedi/links#3]
Hello,

Your project demo looks fantastic - I think it's a much prettier layout than https://github.com/techno-tim/littlelink-server. I was wondering how difficult it would be to package it up for a docker deployment?

Thanks for any thoughts!

**Comment by harsh98trivedi** [comment]
I don't have much experience with Docker, so I believe it'll be quite difficult. However, the project is open-source so I won't mind if someone helps me in packaging it for docker deployment.

**Comment by undaunt** [comment]
I'll start digging into it. I don't have much experience creating my own Dockerfile but I've modified others previously.

**Comment by NelsonDane** [comment]
I just created a PR that adds support for Docker, hopefully that's what you were looking for @undaunt

**Comment by harsh98trivedi** [comment]
Thanks, @NelsonDane! 🙌

**Comment by undaunt** [comment]
This is great, thanks!

Is it possible to have the image regenerate on build, in a way? What I mean is, could we create a bind mount volume requirement pointing to the config file so instead of having to manually rebuild and run on change, we could just restart the container and it would parse the latest version of _config.yml?

**Comment by harsh98trivedi** [comment]
@NelsonDane figured out how to fix this and will surely push the changes soon. He is also planning to host this over DockerHub and sync it with this repository.  I hope you'll surely get a fix soon @undaunt

**Comment by undaunt** [comment]
Hey @harsh98trivedi and or @NelsonDane were you able to pull this into the main repo?

Thanks!

**Comment by NelsonDane** [comment]
I completely forgot about this and got busy with school/life, but I just put a PR in that should fix this issue @undaunt
